### ISSUE TITLE
Create a 0.1.2 release

### ISSUE THREAD

**Issue by lukasgraf** [clarete/forbiddenfruit#14]
The currently released version `0.1.1` on PyPi contains a bug that breaks the standard library in a subtle way, and has been [fixed in master](https://github.com/clarete/forbiddenfruit/pull/13).

Could you please create a new release?

**Comment by jone** [comment]
+1 A release would be awesome! :sparkles:

**Comment by jone** [comment]
Is there anything blocking a release of this awesome package? Can we help make this happen? It would be awesome to have this :relaxed:

**Comment by alexchandel** [comment]
@clarete Could this happen? Preferably with 3.5 support?

**Comment by clarete** [comment]
Sorry for taking forever. I promise next time won't be this painful :/

https://pypi.python.org/pypi/forbiddenfruit/0.1.2

**Comment by mbaechtold** [comment]
Cool, thank you @clarete!
