### ISSUE TITLE
Cursing a reversed curse

### ISSUE THREAD

**Issue by eugene-eeo** [clarete/forbiddenfruit#18]
Example:

``` python
Python 3.5.0 (default, Oct 14 2015, 19:49:57) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from forbiddenfruit import curse, reverse
>>> curse(str, 'one', 1)
>>> str.one
1
>>> reverse(str, 'one')
>>> curse(str, 'one', 2)
>>> str.one
1
```

Is this the expected behaviour? I don't see it documented anywhere and the tests don't seem to cover this 'edge case'.

**Comment by clarete** [comment]
Nops, that does look like a bug! :cry:

**Comment by clarete** [comment]
Hi @Cologler do you think your change for #26 fixed this guy too?

**Comment by Cologler** [comment]
@clarete Yes

**Comment by clarete** [comment]
Nice! Another issue fixed than! Thanks a lot for the contribution! \o/ \o/ \o/
