### ISSUE TITLE
Cursing __init_subclass__

### ISSUE THREAD

**Issue by martmists** [clarete/forbiddenfruit#20]
Since builtins don't have a `__metaclass__` attribute, `__init_subclass__` can be used to at least manipulate this to some degree.

The issue:
```py
In [1]: from forbiddenfruit import curse

In [2]: class x:
   ...:     def __init_subclass__(cls, **kwargs):
   ...:         cls.__init_subclass_o__(**kwargs)  # We can't call __init_subclass__ because recursion
   ...:         print(cls, kwargs)
   ...:         

In [3]: curse(object, "__init_subclass_o__", object.__init_subclass__)

In [4]: curse(object, "__init_subclass__", x.__init_subclass__)

In [5]: class y:
   ...:     pass
   ...: 
<class '__main__.x'> {}

```

As you can tell, no matter what you do, the `cls` argument will ALWAYS be `<class '__main__.x'>`
Creating a regular function (not a method on class x) will result in 
```py
In [6]: def __init_subclass__(cls, **kwargs):
   ...:     cls.__init_subclass_o__(**kwargs)  # We can't call __init_subclass__ because recursion
   ...:     print(cls, kwargs)
   ...:         

In [7]: curse(object, "__init_subclass__", __init_subclass__)

In [8]: class y:
   ...:     pass
   ...: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-9a1635f8452b> in <module>()
----> 1 class y:
      2     pass

TypeError: __init_subclass__() missing 1 required positional argument: 'cls'
```

What should be done here?
Also, will magic methods be patchable yet anytime soon?

**Comment by Julian** [comment]
This used to work (I used it to implement
[composition](https://pypi.org/project/composition/)), but something's changed
recently and broke it (bringing me here).

The timing doesn't work with this ticket -- I think your issue was just you
didn't decorate with `@classmethod`.

**Comment by clarete** [comment]
Hi @martmists, do you think the fix provided by Julian is also enough for your use case? Let me know if it's easy for you to try the version on master temporarily while I release the new (0.2.0) version

**Comment by clarete** [comment]
Please re-open if you find any other issues about this! Thank you <o/
