### ISSUE TITLE
__invert__ operator not supported correctly

### ISSUE THREAD

**Issue by stephenbrodiewild** [clarete/forbiddenfruit#39]
According to the [official documentation](https://docs.python.org/3/reference/datamodel.html#object.__invert__) the dunder method for the invert operator i.e. '~' should be \_\_invert__ rather than \_\_inv__ as currently implemented in init.py (line 267)

**Comment by stephenbrodiewild** [comment]
Apparently [earlier versions of Python (2.7)](https://docs.python.org/2/library/operator.html#operator.__inv__) has support for the \_\_inv__ operator but version 3 only uses \_\_invert__

**Comment by clarete** [comment]
Hi @stephenbrodiewild, thank you for creating the issue \o/
I didn't really investigate deeply, but it seems like this would be as simple as adding a new entry for `invert` around this line: https://github.com/clarete/forbiddenfruit/blob/master/forbiddenfruit/__init__.py#L267.

Do you think you could make that change and see if that works? And if that works, would you be up to opening a Pull Request? :)

Thank you!

**Comment by clarete** [comment]
After merging #40 we might probably close this one! Thank you for reporting *and* fixing the issue, @stephenbrodiewild. Really appreciate it!
