### ISSUE TITLE
Redefine magic methods

### ISSUE THREAD

**Issue by jonathaneunice** [clarete/forbiddenfruit#4]
I was able to redefine `str.lower` very nicely, but `int.__add__` failed to be redefined on either 2.7 or 3.3. For example:

``` python
Python 3.3.0 (v3.3.0:bd8afb90ebf2, Sep 29 2012, 01:25:11)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from forbiddenfruit import curse
>>> def notplus(a,b):
...     return a * b
...
>>> curse(int, '__add__', notplus)
>>> 5 + 9
14
```

**Comment by jab** [comment]
Just found my way here while trying to override `slice` to use a sentinel object rather than `None` for the value of start, stop, and step when the user doesn't pass anything ([background](https://bidict.readthedocs.org/en/master/caveats.html#none-breaks-the-slice-syntax)).

I tried running the following with forbiddenfruit revision feae79ae44b14fd90e18eb5916f6b8e20ea87660 and it didn't work:

```python
from forbiddenfruit import curse

def simpletest(self):
    return 'works'

curse(slice, 'simpletest', simpletest)
assert slice(None).simpletest() == 'works'


def myslice__init__(self, *args, **kw):
    print('myslice__init__')  # never called
    self.start = self.stop = self.step = 42

curse(slice, '__init__', myslice__init__)
print(eval('slice(None).start'))  # doesn't work :(

class myslice:
    def __init__(self, *args, **kw):
        self.start = self.stop = self.step = 42

def myslice__new__(cls, *args, **kw):
    print('myslice__new__')  # never called
    inst = myslice()

curse(slice, '__new__', classmethod(myslice__new__))
print(eval('slice(None).start'))  # doesn't work :(
```
Is there something I'm missing, or is this expected to not work yet?

Thanks for reading, and thanks for releasing forbiddenfruit, it's super cool.

**Comment by jachymb** [comment]
I was trying to redefine the `__mul__` operator for functions so it's do function composition instead. I was trying with forbidden fruit, but it wouldn't work because of this error. But I came up with a different and satisfactory solution, in case someone needs inspiration, I put it here:

```python
import types
__all__ = ['composible']

# This decorator makes function composible by '*' operator with other functions
def composible(f):
    class ComposibleFunction:
        def __init__(self, f):
            self.f = f
        def __call__(self, *a, **kw):
            return self.f(*a, **kw)
        def __mul__(self, g):
            return self.__class__(lambda *a, **kw: self.f(g(*a, **kw)))
    return ComposibleFunction(f)

# Make all builtin function composible:
for b in (b for b in dir(__builtins__)
            if type(getattr(__builtins__,b)) in (type, types.BuiltinMethodType)):
    exec('global '+b+'\n'+b + '=composible(__builtins__.' + b + ')')
    __all__.append(b)

# New functions need to be decorated
@composible 
def foo(x): return x+1

@composible 
def bar(x): return x*2

# This will output 7:
print((foo * bar * sum)([1, 2]))
```

**Comment by voidworker** [comment]
I've found this issue when looking for ability to compose functions like ``f @ g @ h``. While cursing ``object`` with redefined ``__matmul__`` method doesn't work, there is still yet another satisfactory solution, inspired by @jachymb :
```python
from forbiddenfruit import curse
def go(arg, *t):
	s = t[0](*arg)
	for f in t[1:]:
		s = f(s)
	return (s,) # Composability: everybody loves monoids!
curse(tuple,"go", go)
```
usage: ``(x,y,z).go(f, g, h).go(f1,f2)`` turns into ``f2(f1(h(g(f(x,y,z)))))``
```python
(3,4).\
go(lambda x,y: x*y
  ,lambda x: x**2).go(print)
```
```
144
(None,)
```
Of course, one can also define composable functions like ``(some_long_chain).then(f, additional_args_for_f)``. Iterables may also come into play...
Happy functional programming! :)

**Comment by clarete** [comment]
@tomyo I guess you own a beer to @alendit :)

**Comment by clarete** [comment]
Closed by https://github.com/clarete/forbiddenfruit/pull/24

**Comment by davips** [comment]
> I was trying to redefine the `__mul__` operator for functions so it's do function composition instead. I was trying with forbidden fruit, but it wouldn't work because of this error. But I came up with a different and satisfactory solution, in case someone needs inspiration, I put it here:
> 
> ```python
> import types
> __all__ = ['composible']
> 
> # This decorator makes function composible by '*' operator with other functions
> def composible(f):
>     class ComposibleFunction:
>         def __init__(self, f):
>             self.f = f
>         def __call__(self, *a, **kw):
>             return self.f(*a, **kw)
>         def __mul__(self, g):
>             return self.__class__(lambda *a, **kw: self.f(g(*a, **kw)))
>     return ComposibleFunction(f)
> 
> # Make all builtin function composible:
> for b in (b for b in dir(__builtins__)
>             if type(getattr(__builtins__,b)) in (type, types.BuiltinMethodType)):
>     exec('global '+b+'\n'+b + '=composible(__builtins__.' + b + ')')
>     __all__.append(b)
> 
> # New functions need to be decorated
> @composible 
> def foo(x): return x+1
> 
> @composible 
> def bar(x): return x*2
> 
> # This will output 7:
> print((foo * bar * sum)([1, 2]))
> ```

Is there any lib implementing this wonderful?
