### ISSUE TITLE
Add class method to dict?

### ISSUE THREAD

**Issue by bscully27** [clarete/forbiddenfruit#76]
Is it possible to add a class method to python 3.8+ dictionaries?

Goal: dict.keys() or dict.my_added_method() to return list(dict.keys()) for indexing.

My failed attempt:
```
from forbiddenfruit import curse

def attempt(self):
    return list(self.keys())
curse(dict, "my_keys", classmethod(attempt))

d = dict(test=1)
d.my_keys()

```

**Comment by fabiomcosta** [comment]
Hi it sounds like what you are looking for is a method on the dict class instances and not a class method.

Try:
```python
from forbiddenfruit import curse

def attempt(self):
    return list(self.keys())
curse(dict, "my_keys", attempt)

d = dict(test=1)
d.my_keys()
```

**Comment by bscully27** [comment]
Perfect!  Thank you.  
This repo is very cool
